# Generated by Django 4.2.21 on 2025-05-20 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PhysicalDrive",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                (
                    "manufacturer",
                    models.CharField(blank=True, default="Unknown", max_length=255),
                ),
                (
                    "model",
                    models.CharField(blank=True, default="Unknown", max_length=255),
                ),
                (
                    "serial",
                    models.CharField(blank=True, default="Unknown", max_length=255),
                ),
                ("size_bytes", models.BigIntegerField(default=0)),
                (
                    "filesystem_type",
                    models.CharField(blank=True, default="Unknown", max_length=50),
                ),
                ("detected_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Partition",
            fields=[
                (
                    "mount_point",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "physical_drive",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partitions",
                        to="drive_detection.physicaldrive",
                    ),
                ),
            ],
        ),
    ]
