# Generated by Django 4.2.21 on 2025-05-22 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="mediafile",
            new_name="media_media_media_t_72b3fb_idx",
            old_name="media_media_media_t_1c3f21_idx",
        ),
        migrations.RenameIndex(
            model_name="mediafile",
            new_name="media_media_status_936dd8_idx",
            old_name="media_media_status_7c6dac_idx",
        ),
        migrations.AlterField(
            model_name="mediafile",
            name="media_type",
            field=models.CharField(
                choices=[
                    ("video", "VIDEO"),
                    ("audio", "AUDIO"),
                    ("unsupported", "UNSUPPORTED"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="mediafile",
            index=models.Index(
                fields=["catalog_id"], name="media_media_catalog_bf7e29_idx"
            ),
        ),
    ]
